import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '../app/components/header/page'
import '@/assets/styles/global.sass';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="Pt-BR">
      <body className={inter.className}><Header/>{children}</body>
    </html>
  )
}
